// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiElkmNSl0K-N0Rz4kuqKAXrr6Eg7oo64',
    appId: '1:500961952253:web:a846193490974d3667d994',
    messagingSenderId: '500961952253',
    projectId: 'fyptestv2-37c45',
    authDomain: 'fyptestv2-37c45.firebaseapp.com',
    databaseURL: 'https://fyptestv2-37c45-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyptestv2-37c45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMpnsnBC4Sr7NqGvsdlOkCbZKLxE_ObBc',
    appId: '1:500961952253:android:073bf5cb1dd11aae67d994',
    messagingSenderId: '500961952253',
    projectId: 'fyptestv2-37c45',
    databaseURL: 'https://fyptestv2-37c45-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyptestv2-37c45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsiZ1L53ONsGHAzixqpZxRsky2qpgfKX8',
    appId: '1:500961952253:ios:754a068d680670ac67d994',
    messagingSenderId: '500961952253',
    projectId: 'fyptestv2-37c45',
    databaseURL: 'https://fyptestv2-37c45-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyptestv2-37c45.firebasestorage.app',
    iosBundleId: 'com.example.fypPatientV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsiZ1L53ONsGHAzixqpZxRsky2qpgfKX8',
    appId: '1:500961952253:ios:754a068d680670ac67d994',
    messagingSenderId: '500961952253',
    projectId: 'fyptestv2-37c45',
    databaseURL: 'https://fyptestv2-37c45-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyptestv2-37c45.firebasestorage.app',
    iosBundleId: 'com.example.fypPatientV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALnbg189FrMXggq91roPZ6QJeQdqhwlu0',
    appId: '1:500961952253:web:eb688fe5f3f1ebb567d994',
    messagingSenderId: '500961952253',
    projectId: 'fyptestv2-37c45',
    authDomain: 'fyptestv2-37c45.firebaseapp.com',
    databaseURL: 'https://fyptestv2-37c45-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyptestv2-37c45.firebasestorage.app',
  );

}